name: Docker Image CD

on:
    workflow_run:
      workflows: ["Docker Image CI"]
      types:
        - completed


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login into AWS instances
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2HOSTNAME }}
          username: ${{ secrets.EC2USERNAME }}
          key: ${{ secrets.EC2KEY }}

      - name: Install Docker
        run: |
          sudo apt-get update -y
          sudo apt-get install docker.io -y

      - name: Check for usermod is present here
        run: |
          if groups | grep -q docker; then
            echo "USer is already exist"
          else
            echo "User is not a part of group"
            sudo usermod -a -G docker $(whoami)
            newgrp docker
          fi

      - name: Login Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: built the  docekr Images
        run: docker build -t alexkhan2628/ci-cd:latest .

      - name: Run docker Container
        run: docker run -d --name ci-cd-container -p 3000:3000 alexalexkhan2628/ci-cd:latest
