name: Docker Image CD

on:
    workflow_run:
      workflows: ["Docker Image CI"]
      types:
        - completed


jobs:

  build:

    runs-on: self-hosted

    steps:
        - name: Pull the Docker Image
          run: sudo docker pull alexkhan2628/ci-cd:latest

        - name: Old docker container
          run: sudo docker rm -rf ci-cd-container || true

        - name: Run the Docker Container
          run: sudo docker run -d -p 3000:3000 --name ci-cd-container alexkhan2628/ci-cd
          
          
