name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into Docker 
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      
    - name: Build the Docker image
      run: docker build -t ci-cd .

    - name: push to dockerhub
      run: docker push mohamedsathik/ci-cd:latest
