name: Terraform

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.SECRET_KEY }}
      AWS_REGION : "us-east-1"
      
    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout
        uses: actions/checkout@v4      
       
      - name: check
        run: ls && pwd
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        

      - name: Initialize Terraform
        run: terraform init

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply --auto-approve