name: Terraform

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ACCESS KEY AND SECRET KEY
        env:
          ACCESS_KEY : ${{ secrets.ACCESS_KEY }}
          SECRET_KEY : ${{ secrets.SECRET_KEY }}
          
        run: export AWS_ACCESS_KEY="ACCESS_KEY" && export AWS_SECRET_KEY="SECRET_KEY"


      - name: check
        run: ls && pwd
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply --auto-approve